### ISSUE TITLE
Cannot export an instance as OVA

### ISSUE THREAD

**Issue by pranaysahith** [aws/aws-sdk#203] opened 2022-03-11 13:40 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
when an ec2 instance is exported as OVA using `aws ec2 create-instance-export-task` command, it is failing with this error - `An error occurred (NotExportable) when calling the CreateInstanceExportTask operation: The snapshot ID (snap-0bc145ed4603fb16c) of the instance neither is owned by current user nor had been previously imported through VMIE.` This used to work until 2 days back.

**SDK version number**
aws-cli/1.22.71

**Platform/OS/Hardware/Device**
Ubuntu 20

**To Reproduce (observed behavior)**
1. Create an instance
2. Export the instance using `aws ec2 create-instance-export-task` command.

**Expected behavior**
3. It should successfully create OVA in s3 bucket

**Logs/output**
`==> amazon-ebs: An error occurred (NotExportable) when calling the CreateInstanceExportTask operation: The snapshot ID (snap-0030558d83e094ff2) of the instance neither is owned by current user nor had been previously imported through VMIE.`

**Additional context**

**Comment by tim-finnigan** [comment] 2022-03-14 17:48
P61249939

**Comment by trenner02** [comment] 2022-03-14 18:32
We're seeing the same issue.  We've had exports running successfully for years now.  First failure to export in our Jenkins with this error is March 8th (March 3rd was successful), if that helps to track it down.

**Comment by ArkoD** [comment] 2022-03-15 06:44
I am facing the same issue. Have been exporting the same instance for months without any snag. Uptil last week I was able to export ova files. Since yesterday this problem has started 

```
An error occurred (NotExportable) when calling the CreateInstanceExportTask operation: The snapshot ID (xxxx) of the instance neither is owned by current user nor had been previously imported through VMIE.
```

**Comment by susail** [comment] 2022-03-15 15:40
I am facing the same issue as well. The script worked just a couple of days before.
Any update? It blocks our release process.

Here is the command which I used.
`aws ec2 create-instance-export-task --instance-id xxx --target-environment vmware -
-export-to-s3-task DiskImageFormat=vmdk,ContainerFormat=ova,S3Bucket=xxx,S3Prefix=xxx`

`aws-cli/1.21.6 Python/3.8.10 Linux/5.10.16.3-microsoft-standard-WSL2 botocore/1.21.42`

**Comment by bobalo2** [comment] 2022-03-15 18:16
Having the exact same problem as everyone else. Hopefully AWS can figure it out quickly, as we need our exports as soon as possible. 
aws ec2 create-instance-export-task --instance-id id-xxx --target-environment vmware --export-to-s3-task file:///vm-export.json
where vm-export contains: 

{
    "ContainerFormat": "ova",
    "DiskImageFormat": "VMDK",
    "S3Bucket": "mybucket",
    "S3Prefix": "mybucket/"
}

error output: 
An error occurred (NotExportable) when calling the CreateInstanceExportTask operation: The snapshot ID (snap-xxx) of the instance neither is owned by current user nor had been previously imported through VMIE.

The snapshot it mentions does not even exist in my account, but it's probably a temporary one that the export creates and removes afterwards.

**Comment by susail** [comment] 2022-03-15 18:31
The snapshot ID in the error message is always `snap-09c7d0ffed591d4c2`. It is a public snapshot. I don't know how it is related to my EC2 instance.

**Comment by knobel-dk** [comment] 2022-03-15 18:33
> The snapshot ID in the error message is always `snap-09c7d0ffed591d4c2`. It is a public snapshot. I don't know how it is related to my EC2 instance.

For you it might be but look above. The snapshot ids are not identical

**Comment by tim-finnigan** [comment] 2022-03-15 18:37
Thanks all for reporting. This was escalated internally and is being actively investigated. Will post updates here as soon as I have them.

**Comment by susail** [comment] 2022-03-15 19:52
> > The snapshot ID in the error message is always `snap-09c7d0ffed591d4c2`. It is a public snapshot. I don't know how it is related to my EC2 instance.
> 
> For you it might be but look above. The snapshot ids are not identical

Thank you to point it out. It was same for me with multiple EC2 instances. How can a snapshot be related to multiple EC2 instances?

**Comment by luoymu** [comment] 2022-03-15 20:28
Same problem using this command in packer

aws ec2 create-instance-export-task --instance-id ${build.ID} --target-environment vmware --export-to-s3-task DiskImageFormat=vmdk,ContainerFormat=ova,S3Bucket=${var.s3_bucket},S3Prefix=exports

**Comment by kellertk** [comment] 2022-03-17 00:23
Hi everyone, I don't have precise details yet, but a fix for this is currently being deployed. Changes to AWS services (including VM Export) take some time to deploy because we don't make changes to all regions at the same time. Depending on which region you're exporting your VM from/to, this may be working already for you, but we'll provide an update here when the deployment is complete.

**Comment by pranaysahith** [comment] 2022-03-17 07:13
hi @kellertk , we are still facing this issue in Ireland region. Please let us know if the fix is deployed in Ireland region so that we can validate the fix.

**Comment by kellertk** [comment] 2022-03-18 01:08
Hi @pranaysahith - deployment into eu-west-1 completed at 17 Mar 19:27 UTC. At this point, the fix should be deployed in all non-GovCloud regions, so if you're still seeing issues please let us know.

**Closed** 2022-03-18 01:38 UTC
Labels: bug, service-api, ec2

**Comment by pranaysahith** [comment] 2022-03-18 07:32
thank you @kellertk , the issue is resolved.

**Comment by susail** [comment] 2022-03-18 13:38
same here. Issue resolved. Thank you @kellertk

**Comment by trenner02** [comment] 2022-03-18 23:20
Confirmed working for us in us-east-1.  Thank you very much for the quick turnaround on this one!

**Comment by tim-finnigan** [comment] 2022-10-11 16:15
@luoymu which version are you using? Have you tried referring to this troubleshooting guide on VM export errors: https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-troubleshooting.html#instance-export-errors? If you can provide your debug logs (by adding `--debug` to the command) then we can look into this again.

**Comment by uchauhan1994** [comment] 2022-11-17 13:31
I am facing an issue in the us-east-1 region, I am not able to export some images. I am using the below command and version.

**aws ec2 export-image --image-id ami-xxxxxxxxx --disk-image-format VMDK --s3-export-location S3Bucket=xxxxxxxxx,S3Prefix=xxxxxxxxx/** 

**aws-cli/2.8.12 Python/3.9.11 Windows/10 exe/AMD64 prompt/off**

error as below,
**An error occurred (NotExportable) when calling the ExportImage operation: The image ID provided (ami-xxxxxxxxx) is a marketplace AMI and is not exportable.**
