### ISSUE TITLE
Missing AttachmentStatus Available For Internet Gateways

### ISSUE THREAD

**Issue by tlm** [aws/aws-sdk#586] opened 2023-08-15 02:03 UTC
### Describe the bug

The InternetGatewayAttachment struct here https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2/types#InternetGatewayAttachment has an State field for the status that reports "available".

However in the provided enums here https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2/types#AttachmentStatus there is no enum for "available".

It would be nice to get a strongly typed enum from the API to rely on for checking the value.

### Expected Behavior

A typed enum for the value returned from the AWS api.

### Current Behavior

No enum currently provided.

### Reproduction Steps

N/A

### AWS Go SDK V2 Module Versions Used

v1.111.0 of github.com/aws/aws-sdk-go-v2/service/ec2/types

### Compiler and Version used

1.20.0

### Operating System and version

darwin

**Comment by ashishdhingra** [comment] 2024-04-04 20:48
P124948296

**Comment by ashishdhingra** [comment] 2024-04-04 20:49
@tlm I have opened an internal ticket with the service team. Would post any updates here as I get them, and would close this issue once it is in the service team's backlog.

**Comment by ashishdhingra** [comment] 2024-04-24 18:31
Service team is investigating the issue.

**Comment by ashishdhingra** [comment] 2024-07-31 18:28
Service team is still evaluating if adding `Available` to `AttachmentStatus` enum would be a breaking change and if it would pollute other services which share the enum with unnecessary status. As of now, there is no ETA for the change. Since the issue is already with the service team, closing this ticket. If the value `Available` is added to the enum in future via model updates, it would propagate to downstream SDK(s) automatically.

**Closed by ashishdhingra** 2024-07-31 18:28 UTC
Labels: bug, service-api, ec2

**Comment by gravitylow** [comment] 2024-08-08 21:51
Hey all, so unfortunately due to how these structures were originally created and used, we do not have a good way to introduce this change without creating backwards-incompatible changes for someone.

In short, the `AttachmentStatus` enum is currently re-used by a bunch of other EC2 APIs and resources in addition to the Internet Gateway structure. For example the `AttachmentStatus` used by [InstanceNetworkInterfaceAttachment](https://github.com/aws/aws-sdk-net/blob/3939f2dae4f144cc42da592d44058094e95944c0/sdk/src/Services/EC2/Generated/Model/InstanceNetworkInterfaceAttachment.cs#L43), [EbsInstanceBlockDevice](https://github.com/aws/aws-sdk-net/blob/3939f2dae4f144cc42da592d44058094e95944c0/sdk/src/Services/EC2/Generated/Model/EbsInstanceBlockDevice.cs#L40), and [VpcAttachment](https://github.com/aws/aws-sdk-net/blob/3939f2dae4f144cc42da592d44058094e95944c0/sdk/src/Services/EC2/Generated/Model/VpcAttachment.cs#L37) are all the same enum. This is not good practice but now that it's done, it's done, and we can't change the enum used by one or more of them to differentiate them without breaking strongly-typed SDKs.

We could add the `available` status to the shared enum, but this would also add the value to these other usecases where it is not valid and may cause more confusion and/or need to be accounted for by SDK users' switch statements and the like.

The other alternative is obviously updating the actual value returned by the Internet Gateway APIs to use `attached` or one of the existing values that are enumerated in the SDK, but again this has the potential to be backwards-breaking, especially since this behavior is more than 10 years old.

So, all in all, our guidance in this situation has to be to disregard the `AttachmentStatus` enum and simply maintain `available` as a constant value to check for. That's the only possible value for this field, and although it seems weird, given how long the behavior has been in place I can assure you it won't be changing any time soon. If anyone has a better proposal for how to handle this scenario without breaking customers, please do add your thoughts!

**Comment by tlm** [comment] 2024-08-10 07:12
Thank you for the update. We will keep maintaining our own enum in (Juju)[github.com/juju/juju].
