### ISSUE TITLE
Redshift Data API Service: Problem with COPY command

### ISSUE THREAD

**Issue by dburtsev** [aws/aws-sdk#333] opened 2022-08-23 20:29 UTC
Hello

ResultRows from boto3 describe_statement always return 0 when executing COPY command.

```
import boto3
def ExecuteCopy(Boto3Client,ClusterIdentifier,Database,DbUser,Sql):
    rows = 0
    Response1 = Boto3Client.execute_statement(ClusterIdentifier=ClusterIdentifier,Database=Database,DbUser=DbUser,Sql=Sql)
    Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    while Response2['Status'] in ['PICKED', 'STARTED', 'SUBMITTED']:
        Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    if Response2['Status'] != 'FINISHED':
        print("Expect FINISHED got " + Response2['Status'])
        raise ValueError("Expect FINISHED got " + Response2['Status'] + ' ' + Response2['Error'])
    rows = int(Response2["ResultRows"])
    return rows

sql_client = boto3.client('redshift-data', region_name = 'us-east-1')
ClusterIdentifier = 'qwe'
Database = 'qwe'
DbUser = 'qwe'
sql = "COPY dev.copy_test FROM 's3://xyz/adhoc/copy_test.csv' FILLRECORD REMOVEQUOTES ESCAPE;"

i = ExecuteCopy(sql_client,ClusterIdentifier,Database,DbUser,sql)
print(i)
```
This is related to https://github.com/aws/aws-sdk/issues/322
Note: ResultRows works correctly after the INSERT command.

**Comment by dburtsev** [comment] 2022-08-23 20:36
```
CREATE TABLE dev.copy_test
(
	id INTEGER,
	txt VARCHAR(20)
);
```
[copy_test.csv](https://github.com/aws/aws-sdk/files/9410493/copy_test.csv)

**Comment by aBurmeseDev** [comment] 2022-08-30 06:52
Hi @dburtsev, thanks for reaching out and sorry to hear that you're having an issue.

I'm trying to understand how this one is different from the similar issue you mentioned [#322](https://github.com/aws/aws-sdk/issues/322). Upon reviewing the other issue, you mentioned that using `pg_last_copy_count()` function, boto3 returns 0 and `COPY` command also appeared in the code snippet as this one has it as well. 

Could you elaborate a bit more on what exactly you’re trying to do and perhaps share your debug logs?

**Comment by dburtsev** [comment] 2022-08-30 13:08
Hi @aBurmeseDev 

#322 was about two issue - pg_last_copy_count() for COPY command and pg_last_query_id() for INSERT command.
This new issue is only for COPY command. I can get number of records after INSERT command using describe_statement ResultRows.  
I can't get number of records after COPY command. describe_statement ResultRows return 0.

**Comment by aBurmeseDev** [comment] 2022-08-30 22:48
Thank you for sharing additional information. Could you also post your debug logs by adding `boto3.set_stream_logger('')` to your script?

Since the issue is also related to Service API, I'd also suggest reaching out to [AWS Support](https://aws.amazon.com/contact-us/) for help or consider asking in [re:Post Forum](https://repost.aws/tags/TAByF7MpfSQUCX_lAeDTvODw/amazon-redshift).

**Comment by dburtsev** [comment] 2022-08-31 13:12
Hi @aBurmeseDev 
Log is attached
[stream_logger.txt](https://github.com/aws/aws-sdk/files/9461784/stream_logger.txt)

**Comment by aBurmeseDev** [comment] 2022-08-31 17:46
Thanks for providing the logs. I reached out to Redshift API team and they will be looking into it shortly. I will post an update as soon as I hear back.

**Comment by aBurmeseDev** [comment] 2022-08-31 19:35
P70939979

**Comment by aBurmeseDev** [comment] 2024-05-17 19:44
Hi @dburtsev - I just heard back from the service team that the behavior you described is expected default behavior for COPY queries and not a bug but the team will further look into modifying it without breaking current applications. 

Since this's more service API related rather than SDK, please look out for updates/announcements from Glacier team as I'll be closing this.

**Closed by aBurmeseDev** 2024-05-17 19:44 UTC
Labels: bug, service-api, redshift-data
