### ISSUE TITLE
formatting typo:   ... a value for IPAddress ** ...

### ISSUE THREAD

**Issue by stuartcrobinson** [aws/aws-sdk#31] opened 2020-12-11 17:45 UTC
formatting error / typo here:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/route53/create-health-check.html

**currently is:**

> **If you don’t specify a value for IPAddress ** 

**should be:**

> **If you don’t specify a value for IPAddress**

**Comment by kdaily** [comment] 2021-08-11 21:56
V413243182

**Comment by kdaily** [comment] 2021-08-12 22:32
Hi @stuartcrobinson - the issue is being fixed by the documentation team. It may take some time to hit the docs pages. I'm going to close this as the impact is minimal.

Thanks again for the attention to detail!

**Closed by kdaily** 2021-08-12 22:32 UTC
Labels: documentation, feature-request, route53
