### ISSUE TITLE
SSO session expiration and re-login

### ISSUE THREAD

**Issue by villelahdenvuo** [aws/aws-sdk#531] opened 2022-10-25 16:18 UTC
### Describe the bug

I'm using AWS SSO to authenticate and aws-sdk-js-v3. When the SSO session expires it tells me to log in again with an error message, but even after repeating the aws sso login, the credentials still don't work.

### Expected Behavior

The Node server is able to load credentials again and I can keep developing.

### Current Behavior

The error message persists.

### Reproduction Steps

1. I log in normally using `aws sso login --profile developer`
2. I start my Node.js server: `AWS_PROFILE=developer node server.js`
3. I keep developing my app until my SSO session expires
4. aws-sdk-js-v3 throws an error:

> CredentialsProviderError: The SSO session associated with this profile has expired. To refresh this SSO session run aws sso login with the corresponding profile

5. I login again `aws sso login --profile developer`
6. Same error is thrown again when I try to call some aws-sdk-js-v3 command.

### Additional Information/Context

I opened my `.aws/sso/cache/xxx.json` file and notice that the `accessToken` **is updated** however the `expiresAt` property **is not updated** even after a new `aws sso login` call. 

If I wait more time and run aws sso login again it finally updates the `expiresAt` property.

It seems that this is a likely reason for the issue I'm having. It seems like there is some mismatch with different expirations.

### CLI version used

aws-cli/2.8.2 Python/3.10.7 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS

**Comment by benkehoe** [comment] 2023-05-03 00:20
For the record, my position is that SDKs should not refuse to use a token that hasn't expired yet. An expiration window is great for _refreshing_ credentials so that there's no gap where the SDK only has expired credentials, but it just doesn't make sense to be like "well, this might not work in 15 minutes, so better stop using it now".

**Comment by spoco2** [comment] 2023-07-05 05:19
Just want to raise here that the issue mentioned ☝️ regarding `cdk cli` seemingly never triggering any sort of refresh, and so always having session timeouts set to 1 hour has been linked to this as the root cause.

Want to ensure that it's not a related issue that may not be fixed with any fix created for this. Other threads had surmised that using the `aws cli` triggered refreshes of the tokens as required, but the `cdk cli` didn't use `aws cli` and so didn't trigger any of the required token refreshes, and so was always only getting the initial 1 hour session, regardless of what the session length was set to against the Permission Set associated with the user and account they were logging into via SSO.

Thank you to @benkehoe for the detailed breakdown of the flows involved.

If anyone happens to know of any workarounds until this is solved, it would be wonderful.

The issue of there being a 15 minute window of the system saying the token is invalid, but also not allowing a new one to be refreshed is not what we're hitting, but rather our sessions being always 1 hour long no matter what I have them set to within the Permission Set (12 hours).

**Comment by gastonsilva** [comment] 2023-07-06 14:04
@spoco2 a workaround I found is to run any command with aws-cli on the sso-session profile before using cdk (something simple like `aws S3 ls --profile my-sso-session-profile`), this performs a renovation and avoids the need to make a full sso-login which might be slower. There are several ways to do this depending on your project structure and language.
For example you can include a line in your cdk/bin to spawn the command, if using npm adding the AWS command to a script, etc.
Hope this helps!

**Comment by spoco2** [comment] 2023-07-11 00:22
@gastonsilva , thanks. I was thinking something like that, or a cron job to do that every 10 minutes or so would be something to keep it alive in the meantime!

**Closed** 2023-07-24 19:49 UTC
Labels: bug, service-api, sso

**Comment by benkehoe** [comment] 2023-07-24 20:32
@tim-finnigan Just to confirm, have all the other AWS SDKs been checked for this problem?

**Comment by tim-finnigan** [comment] 2023-07-24 21:12
@benkehoe Yes we had members from each SDK team review and confirm, only the Java and JavaScript SDKs were found to have this issue.

**Comment by jamsmd** [comment] 2023-07-26 20:43
I had the same issue. I'm using ARC browser and the `aws sso login` command triggered mini arc and whenever I finish the auth process in mini arc I would get the error. 

Whenever the `aws sso login` command opens mini arc click the right top to open the auth proces in regular arc.

That did the trick for me!

**Comment by Nadinee77** [comment] 2024-05-12 19:31
Does anyone know anything about when the [sso](https://ssoidportal.org/) session will expire
