### ISSUE TITLE
Support of http_proxy and https_proxy in config file

### ISSUE THREAD

**Issue by AlexVulaj** [aws/aws-sdk#538] opened 2023-05-16 20:39 UTC
### Describe the feature

Currently, using an http/https proxy for commands requires exporting HTTP_PROXY or HTTPS_PROXY as an environment variable as per [the existing docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html). It would be convenient if these proxies could instead be declared in configuration specific to the AWS CLI to encapsulate the change.

### Use Case

As a user, I would like to set an https_proxy that my aws-cli always uses so that I am always accessing our customers' resources through a published, company owned IP. Setting this in a configuration file one time would allow this change to survive terminal restarts, as well as prevent the environment variable from needlessly impacting other terminal commands.

### Proposed Solution

When running commands, the AWS CLI should check for the existence of a proxy variable in `~/.aws/config` (or `%UserProfile%\.aws\config` on Windows) and use that when making calls.

### Acknowledgements

- [X] I may be able to implement this feature request
- [x] This feature might incur a breaking change

### CLI version used

aws-cli/2.11.12

### Environment details (OS name and version, etc.)

Darwin/22.4.0 source/arm64

**Comment by Mythra** [comment] 2023-07-12 02:43
Hey I just got pointed to this from our PR adding support for the environment variables for proxies to .NET! Let me know if we can be of any help discussing what to do with overarching decisions (whether it be adding use cases about why it's useful, or something else)! We'd be happy to do whatever we could. 

For the three clients that don't support this proxying today (via environment variables -- Rust, Java-v2, and .NET) we had planned on opening PRs for each (though we only have PRs open for the two GA clients right now -- Java-v2 & .NET). We'll hold off on that third PR for now to not cause any extra work, but are very interested in getting this supported on every single SDK. Having it configuration too would be really nice!

**Comment by kellertk** [comment] 2024-05-09 21:08
This is a duplicate of #127 . Closing here to track there.

**Closed by kellertk** 2024-05-09 21:08 UTC
Labels: feature-request, cross-sdk
