### ISSUE TITLE
S3 DeleteObjects API returns `MalformedXML...` error when trying to delete >1000 objects

### ISSUE THREAD

**Issue by sdarwin** [aws/aws-sdk#602] opened 2023-09-12 00:03 UTC
### Describe the feature

Improve the accuracy of the error messages during certain failures.

### Use Case

Clear error messages assist in debugging.

Here is the problem I encountered. When running this command to delete objects in S3:

```
aws s3api delete-objects --profile $PROFILE --bucket $BUCKET --delete file://list.json
```
It supposedly has a limit of 1000 items. If you provide a million items to delete, the error messages are mysterious:

```
SSL validation failed for https://s3.amazonaws.com/_my_bucket_?delete EOF occurred in violation of protocol (_ssl.c:2427)
```

or

```
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
```

As evidence for MalformedXML error, consider [this stackexchange article ](https://stackoverflow.com/questions/45727244/malformedxml-the-xml-you-provided-was-not-well-formed-or-did-not-validate-again)

"+1 for number of keys. I did not check the go code but for us in python boto3 over 1000 keys in the request caused the error. You would think they would document this is the documentation for MalformedXML on the sdk client, but you did find api documentation. We chunked the keys and it works perfect – [vfrank66](https://stackoverflow.com/users/3870664/vfrank66)"

### Proposed Solution

The problem is that neither message explains the actual cause of the problem, which is the input is over 1000 items in length.  The errors should be more specific about the real reason.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.17 Python/3.11.5 Linux/6.2.0-1013-gcp exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by tim-finnigan** [comment] 2023-09-15 16:53
P99874682

**Comment by sdarwin** [comment] 2023-09-15 17:47
> The SSL validation failed...  if it was something that you just encountered once

Just retesting now.  

Ok, there is a different reason for the SSL error. It isn't the 1000 item limit, which I had thought.

```
SSL validation failed for https://s3.amazonaws.com/_bucket_?delete EOF occurred in violation of protocol (_ssl.c:2427)
```

That is caused by not specifying the region.    Notice how https://s3.amazonaws.com/ seems to be a generic endpoint, without mentioning a region.   

If I add `--region us-east-2` to the command, it's fixed.

Well, that is another one to consider then?  The user does not see a message such as  "You should set the region."   Simply a unknown SSL error.

**Comment by tim-finnigan** [comment] 2023-09-15 17:58
The SSL validation error doesn't seem directly related to S3. A [few other issues](https://github.com/issues?q=is%3Aissue+%22SSL+validation+failed%22+%22EOF+occurred+in+violation+of+protocol%22+repo%3Aaws%2Faws-cli+is%3Aclosed) have reported that error and it could be caused by various things. If you add `--debug` to your command then it may provide more insight, but if it's not a certificate or proxy issue then it could be an issue with whichever version of urllib3 or OpenSSL you have installed. I can't reproduce the error just by not providing a region.

**Comment by sdarwin** [comment] 2023-09-15 19:33
This is a going off track now.  :-)    I will post the info, just to be complete, anyway.

Collecting a list of items, that will later be deleted:

```
    aws s3api list-object-versions --max-items 1002  --profile $PROFILE \
        --bucket $BUCKET \
        --output=json \
        --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}' --prefix $PREFIX > list.json
```

Because that is over 1000, it causes an error. In this case,  (MalformedXML)

What if the number of items is larger, 10,000 instead?

```
    aws s3api list-object-versions --max-items 10000  --profile $PROFILE \
        --bucket $BUCKET \
        --output=json \
        --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}' --prefix $PREFIX > list.json
```

Now, it seems that a combination of all these factors:

- a large list of items (10000), 
- no region being specified, either on the command line, or in .aws/config, or in /aws/credentials.  (actually, I had a default in .aws/config)
- using a non-default region ( us-east-2 instead of us-east-1)

Gets this error:

```
SSL validation failed for https://s3.amazonaws.com/_bucket_?delete EOF occurred in violation of protocol (_ssl.c:2427)
```

It can be resolved by reducing the number of items or adding the --region.  Either one. That at least gets back to "MalformedXML".

**Comment by tim-finnigan** [comment] 2024-09-25 19:35
Thanks for your patience. I don't have any updates as of now, but the S3 team is continuing to track the request to improve the error message in their backlog for consideration. We're going to close this on our end as the service team would need to take the next steps here. Please refer to the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for updates, or feel free to reach out through support if you have a support plan.

**Closed by tim-finnigan** 2024-09-25 19:35 UTC
Labels: feature-request, service-api, s3
