### ISSUE TITLE
Slow upload speed in Apple Virtualization Framework VMs on M1

### ISSUE THREAD

**Issue by remarkov** [aws/aws-sdk#469] opened 2022-11-26 05:11 UTC
### Describe the bug

We noticed that uploading speed is dramatically slow if running on an M1 VM under native Apple Virtualization Framework. No matter what the file size is, transfer speed gets 10x+ slower than normal if AWS CLI is used on a virtual machine compared to the same test performed on the host running this VM rather than in VM itself. I tried different hosts and different apps that use Apple virtualization, namely [Tart](https://github.com/cirruslabs/tart/) and [VirtualBuddy](https://github.com/insidegui/VirtualBuddy).

I would think that the Apple Virtualization has network issues in general but the network performance in other tools like scp, rsync, gcloud etc. stays fine, just AWS CLI gets affected so I believe it may be of interest for the maintainers here to investigate what may cause this.

### Expected Behavior

The upload speed should be the same when using both Intel and ARM hosts given they have no other difference in network setup, bandwidth limits etc.

### Current Behavior

The upload speed is ~10x slower on M1 Apple Virtualization Framework VMs than on any other host or other type of VM.

### Reproduction Steps

1. Create a VM via M1 native Apple Virtualization Framework using any of the tools like [Tart](https://github.com/cirruslabs/tart/) and [VirtualBuddy](https://github.com/insidegui/VirtualBuddy). OS version does not matter be it Monterey or Ventura.
2. Install and configure awscli.
3. Run the following commands and observe the transfer speed:

```
> dd if=/dev/urandom of=sample.txt bs=8M count=1
> aws s3 cp sample.txt s3://my-bucket
```

On the smaller files the issue is easier to observe because on bigger files the threading more or less compensates the slower speed.

### Additional Information/Context

As advised by @aBurmeseDev I duplicate this information into the new issue as the [initial one](https://github.com/aws/aws-cli/issues/7299) got closed too early. I also updated the description with the actual information.

### CLI version used

2.8.2

### Environment details (OS name and version, etc.)

Tart VM running macOS 12.6 M1

**Comment by aBurmeseDev** [comment] 2023-02-28 09:24
Hi all - thank you for your patience while we investigate. We wanted to provide an update and share our findings here. We performed multiple testing with different SDKs to gather data and performance benchmarks. Here's our latest finding while testing with Fedora.

We installed VMWare Fusion and the latest CLI v2 on the host OS. Started up a new VM, running Fedora and updated the guest OS, installed CLIv2 on the guest OS as well. Then we tested network bandwidth on the host as well as the guest (VM). We observed the same issue where host would only take less than a minute while the VM took a few minutes. 

So we installed TuneD in the guest. TuneD is a daemon that automatically sets sysctls/kernel parameters. We ran the command `tuned-adm profile network-throughput virtual-guest` which applies the network-throughput performance profile first, and then applies the virtual-guest profile on top of it, overriding the underlying settings. Then, we tested network bandwidth again in the guest and observed the speed about 8 megabytes per second which is much closer to the host speed.

We think that the network TCP kernel settings that tuneD adjusted with is the cause of the speed up and that would be because there’s some optimization happening with the Apple Silicon virtualized instructions and the way the para-virtualized network adapter is working. Changing the receive window seems to fix it.

All things considered, we came to the conclusion that this isn't a bug with S3 or the SDK but rather due to some default network configuration with Apple Silicon Virtualization. For now, we would suggest using AWS Console as a workaround or consider using performance monitoring and configuration tools to optimize the performance under certain workloads.

**Comment by liamnichols** [comment] 2023-02-28 09:55
Thanks for following up on this @aBurmeseDev! 

> we came to the conclusion that this isn't a bug with S3 or the SDK **but rather due to some default network configuration with Apple Silicon Virtualization**

I mentioned it in the Ruby SDK ticket, but I filed a Feedback with Apple as [FB11858528](http://www.openradar.me/radar?id=5505543569408000) so if anybody else is being impacted by this, please consider duping it (and/or submitting a TSI) to try and get a response from Apple

**Comment by timsutton** [comment] 2023-05-03 00:34
I don't think anyone in this thread has mentioned the choice of NAT vs. bridged networking interface in the Apple Virtualization VM. Is there any additional data points there, e.g. is the performance degradation the same?

**Comment by cadecairos** [comment] 2023-09-14 16:08
A colleague of mine found an interesting workaround for this issue (although one we would **not** recommend relying on). 

It was discovered that uploads to AWS from with an Apple Virtualization Framework VM would not be slow if we pinned the S3 endpoint IPs to `3.5.0.0/19` via `/etc/hosts` (This range is advertised for S3 here [https://ip-ranges.amazonaws.com/ip-ranges.json](https://ip-ranges.amazonaws.com/ip-ranges.json))

Here's a PoC (`bucket_name` should be changed to the target bucket, i.e. "github-cloud" for GitHub LFS):

```
bucket_name="YOUR_BUCKET_NAME"
rr_rw_soa="$(host -t SOA s3-r-w.us-east-1.amazonaws.com | grep -o '[^ ]\{1,\}\.awsdns-[^ ]\{1,\}')"
rr_rw_a="$(timeout 2s bash -c "while ! host s3-r-w.us-east-1.amazonaws.com '${rr_rw_soa}' | grep -o '3\.5\.[0-9]\{1,\}\.[0-9]\{1,\}'; do continue; done")"

rr_w_soa="$(host -t SOA s3-w.us-east-1.amazonaws.com | grep -o '[^ ]\{1,\}\.awsdns-[^ ]\{1,\}')"
rr_w_a="$(timeout 2s bash -c "while ! host s3-w.us-east-1.amazonaws.com '${rr_w_soa}' | grep -o '3\.5\.[0-9]\{1,\}\.[0-9]\{1,\}'; do continue; done")"

sudo tee -a /etc/hosts <<EOD
$(head -n 1 <<<"${rr_rw_a}") "${bucket_name}.s3.us-east-1.amazonaws.com"
$(head -n 1 <<<"${rr_w_a}") "${bucket_name}.s3.amazonaws.com"
EOD
```

In our testing, a 10MB git-lfs push took 6 seconds with this fix, and > 90 seconds without it.

We're not sure what exactly is causing such a significant performance difference between the IPs in `3.5.0.0/19` and any other valid S3 service IPs, but it does seem to suggest the problem isn't entirely related to the TCP configuration on the guest and host.

**Comment by Hoverbear** [comment] 2024-03-28 18:33
I encountered this today on a CircleCI machine and found this in their documentation: https://support.circleci.com/hc/en-us/articles/19334402064027-Troubleshooting-slow-uploads-to-S3-for-jobs-using-an-m1-macOS-resource-class

Running `sudo sysctl net.inet.tcp.tso=0` in the CI machine appears to have resolved the issue adequately.

**Comment by kellertk** [comment] 2024-06-06 20:37
Closing this issue as this does not appear to be a problem with the SDK or the S3 service.

**Closed by kellertk** 2024-06-06 20:37 UTC
Labels: bug, s3
