### ISSUE TITLE
 Add waiter support for Batch DescribeJobs

### ISSUE THREAD

**Issue by cariaso** [aws/aws-sdk#712] opened 2024-03-28 16:37 UTC
https://github.com/boto/botocore/pull/1307
https://github.com/aws/aws-sdk/issues/84
@jmklix Can you indicate what commit completes this work and supports closing this issue?

**Comment by kellertk** [comment] 2024-04-02 01:32
Hello! This was closed in https://github.com/boto/botocore/pull/1307 and our stance on why this was closed is in that issue, and in #84, which I think you participated in as well.

The reason is that much of the individual service clients in the SDKs are code generated from model files, including support for different service APIs, and waiters and paginatiors. The internal teams that develop and run the different AWS services own their models, and provide the SDK development teams with the models which we then build and release. Doing it this way ensures that all of our SDKs are mostly consistent and correct, but that means that most of the SDK is no longer a hand-written client as it was in the past. The proper place to implement this is in the service's model description file.

When we receive a feature request such as this, we notify the team responsible with an internal ticket, because most AWS teams are not present on GitHub. We had in the past also left the GitHub issue open, but found that there were a significant number of issues that stayed open even as service teams made changes, simply because internal teams don't announce new changes via GitHub and don't close the loop with the SDK team on new features. To stop the possibility of invalid issues remaining open, our stance for this repository is to now close issues once internal teams have confirmed the bug or feature request and placed an item on their own internal backlog. Within the last few weeks we have begun closing older issues once we've reconfirmed that the responsible team is engaged and aware of the issue.

Unfortunately, GitHub's closure options for an issue gives you two options: Close as completed (default) or Close as not planned. This can be misleading: the issues should have been closed in a way to indicate "Closed as planned but not completed yet", which is how we would have categorized this. In order to make this more clear, I will close this issue as not planned now, because we did confirm that the responsible team is aware of the feature gap.

**Closed by kellertk** 2024-04-02 01:32 UTC
